use_frameworks!

platform :ios, '8.0'

target 'HelloTest_Example' do
  pod 'HelloTest', :path => '../'

  target 'HelloTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
